"""Data contract models — the source of truth for the API schema.

JSON output uses camelCase via alias_generator. Python code stays snake_case.
TypeScript interfaces are generated by Orval from the OpenAPI spec.

All physical quantities use aviation-standard units with explicit suffixes:
  - Altitude: feet (_ft)
  - Speed: knots (_kts)
  - Vertical rate: feet per minute (_fpm)
  - Track/heading: degrees (no suffix, convention)

Types are strict to match the airplanes.live API:
  - alt_baro, alt_geom, baro_rate → int (never float in the API)
  - gs, track → float (always have decimals in the API)
"""

from typing import Literal

from pydantic import BaseModel, ConfigDict
from pydantic.alias_generators import to_camel

PositionSource = Literal["ADS-B", "MLAT", "TIS-B", "ADS-C", "Mode S", "Unknown"]


class AircraftState(BaseModel):
    """One aircraft's state from the airplanes.live API."""

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)

    icao24: str
    callsign: str | None
    registration: str | None
    aircraft_type: str | None
    category: str
    latitude: float
    longitude: float
    baro_altitude_ft: int | None
    geo_altitude_ft: int | None
    ground_speed_kts: float | None
    true_track: float | None
    vertical_rate_fpm: int | None
    on_ground: bool
    squawk: str | None
    last_contact: int
    position_source: PositionSource
    is_climbing: bool
    is_descending: bool
    destination: Literal["LHR", "LGW", "STN", "LTN", "LCY"] | None


class KPIs(BaseModel):
    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)

    tracked_aircraft: int
    airborne_aircraft: int
    inbound_london_aircraft: int
    climbing_aircraft: int
    descending_aircraft: int
    throughput_last_60min: int
    avg_altitude_ft: int | None
    api_health: Literal["live", "stale", "offline"]


class AircraftResponse(BaseModel):
    """Single response for the main polling endpoint."""

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)

    timestamp: int
    cache_age_seconds: float
    refresh_interval_ms: int
    aircraft: list[AircraftState]
    kpis: KPIs


class AirportWeather(BaseModel):
    """Weather data for a specific airport via MET Norway."""

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)

    icao: str
    name: str
    condition: str  # e.g., "clearsky_day", "rain", "cloudy"
    temperature_c: float | None
    wind_speed_kts: float | None
    wind_direction_deg: float | None


class WeatherResponse(BaseModel):
    """Single response for the weather polling endpoint."""

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)

    timestamp: int
    cache_age_seconds: float
    weather: list[AirportWeather]


class HeatmapHexagon(BaseModel):
    """Aggregated heatmap data for a single H3 hexagon."""

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)

    hex_id: str
    total_volume: int
    avg_altitude: float
