/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Flight Tracker at Home API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { fetchClient } from '../lib/fetch-client';
/**
 * One aircraft's state, transformed from OpenSky's positional array.
 */
export interface AircraftState {
  icao24: string;
  callsign: string | null;
  originCountry: string;
  latitude: number;
  longitude: number;
  baroAltitude: number | null;
  geoAltitude: number | null;
  velocity: number | null;
  trueTrack: number | null;
  verticalRate: number | null;
  onGround: boolean;
  squawk: string | null;
  lastContact: number;
  isApproachingLhr: boolean;
}

export type KPIsApiHealth = typeof KPIsApiHealth[keyof typeof KPIsApiHealth];


export const KPIsApiHealth = {
  green: 'green',
  amber: 'amber',
  red: 'red',
} as const;

export interface KPIs {
  inboundLhr: number;
  throughputLast60Min: number;
  trackedAircraft: number;
  dataFreshnessSeconds: number;
  apiHealth: KPIsApiHealth;
}

/**
 * Single response for the main polling endpoint.
 */
export interface AircraftResponse {
  timestamp: number;
  cacheAgeSeconds: number;
  aircraft: AircraftState[];
  kpis: KPIs;
}

/**
 * Simple health check for Render deployment.
 * @summary Health Check
 */
export type getHealthResponse200 = {
  data: unknown
  status: 200
}

export type getHealthResponseSuccess = (getHealthResponse200) & {
  headers: Headers;
};
;

export type getHealthResponse = (getHealthResponseSuccess)

export const getGetHealthUrl = () => {




  return `/health`
}

export const getHealth = async ( options?: RequestInit): Promise<getHealthResponse> => {

  return fetchClient<getHealthResponse>(getGetHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetHealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }


export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: QueryKey }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = unknown


/**
 * @summary Health Check
 */

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * Main polling endpoint.
Fetches the lazy-cached state, abstracting the OpenSky API rate limits.
 * @summary Get Aircraft State
 */
export type getAircraftResponse200 = {
  data: AircraftResponse
  status: 200
}

export type getAircraftResponseSuccess = (getAircraftResponse200) & {
  headers: Headers;
};
;

export type getAircraftResponse = (getAircraftResponseSuccess)

export const getGetAircraftUrl = () => {




  return `/aircraft`
}

export const getAircraft = async ( options?: RequestInit): Promise<getAircraftResponse> => {

  return fetchClient<getAircraftResponse>(getGetAircraftUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAircraftQueryKey = () => {
    return [
    `/aircraft`
    ] as const;
    }


export const getGetAircraftQueryOptions = <TData = Awaited<ReturnType<typeof getAircraft>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAircraft>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAircraftQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAircraft>>> = ({ signal }) => getAircraft({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAircraft>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAircraftQueryResult = NonNullable<Awaited<ReturnType<typeof getAircraft>>>
export type GetAircraftQueryError = unknown


/**
 * @summary Get Aircraft State
 */

export function useGetAircraft<TData = Awaited<ReturnType<typeof getAircraft>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAircraft>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAircraftQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}
