/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Flight Tracker at Home API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { fetchClient } from './fetch-client';
/**
 * One aircraft's state, transformed from OpenSky's positional array.
 */
export interface AircraftState {
  icao24: string;
  callsign: string | null;
  originCountry: string;
  latitude: number;
  longitude: number;
  baroAltitude: number | null;
  geoAltitude: number | null;
  velocity: number | null;
  trueTrack: number | null;
  verticalRate: number | null;
  onGround: boolean;
  squawk: string | null;
  lastContact: number;
  positionSource: string;
  category: string;
  isApproachingLhr: boolean;
}

export type KPIsApiHealth = typeof KPIsApiHealth[keyof typeof KPIsApiHealth];


export const KPIsApiHealth = {
  live: 'live',
  stale: 'stale',
  offline: 'offline',
} as const;

export interface KPIs {
  trackedAircraft: number;
  airborneAircraft: number;
  inboundLhrAircraft: number;
  climbingAircraft: number;
  descendingAircraft: number;
  throughputLast60Min: number;
  avgAltitudeFt: number | null;
  apiHealth: KPIsApiHealth;
  apiCreditsRemaining: number | null;
}

/**
 * Single response for the main polling endpoint.
 */
export interface AircraftResponse {
  timestamp: number;
  cacheAgeSeconds: number;
  refreshIntervalMs: number;
  aircraft: AircraftState[];
  kpis: KPIs;
}

/**
 * Weather data for a specific airport via MET Norway.
 */
export interface AirportWeather {
  icao: string;
  name: string;
  condition: string;
  temperatureC: number | null;
  windSpeedKts: number | null;
  windDirectionDeg: number | null;
}

/**
 * Single response for the weather polling endpoint.
 */
export interface WeatherResponse {
  timestamp: number;
  cacheAgeSeconds: number;
  weather: AirportWeather[];
}

/**
 * Simple health check.
 * @summary Health Check
 */
export type getHealthResponse200 = {
  data: unknown
  status: 200
}

export type getHealthResponseSuccess = (getHealthResponse200) & {
  headers: Headers;
};
;

export type getHealthResponse = (getHealthResponseSuccess)

export const getGetHealthUrl = () => {




  return `/health`
}

export const getHealth = async ( options?: RequestInit): Promise<getHealthResponse> => {

  return fetchClient<getHealthResponse>(getGetHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetHealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }


export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: QueryKey }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = unknown


/**
 * @summary Health Check
 */

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * Main polling endpoint.
Fetches the lazy-cached state, abstracting the OpenSky API rate limits.
 * @summary Get Aircraft State
 */
export type getAircraftResponse200 = {
  data: AircraftResponse
  status: 200
}

export type getAircraftResponseSuccess = (getAircraftResponse200) & {
  headers: Headers;
};
;

export type getAircraftResponse = (getAircraftResponseSuccess)

export const getGetAircraftUrl = () => {




  return `/aircraft`
}

export const getAircraft = async ( options?: RequestInit): Promise<getAircraftResponse> => {

  return fetchClient<getAircraftResponse>(getGetAircraftUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAircraftQueryKey = () => {
    return [
    `/aircraft`
    ] as const;
    }


export const getGetAircraftQueryOptions = <TData = Awaited<ReturnType<typeof getAircraft>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAircraft>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAircraftQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAircraft>>> = ({ signal }) => getAircraft({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAircraft>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAircraftQueryResult = NonNullable<Awaited<ReturnType<typeof getAircraft>>>
export type GetAircraftQueryError = unknown


/**
 * @summary Get Aircraft State
 */

export function useGetAircraft<TData = Awaited<ReturnType<typeof getAircraft>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAircraft>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAircraftQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * Diagnose OpenSky API connectivity from this server.
 * @summary OpenSky Connectivity Test
 */
export type debugOpenskyResponse200 = {
  data: unknown
  status: 200
}

export type debugOpenskyResponseSuccess = (debugOpenskyResponse200) & {
  headers: Headers;
};
;

export type debugOpenskyResponse = (debugOpenskyResponseSuccess)

export const getDebugOpenskyUrl = () => {




  return `/debug/opensky`
}

export const debugOpensky = async ( options?: RequestInit): Promise<debugOpenskyResponse> => {

  return fetchClient<debugOpenskyResponse>(getDebugOpenskyUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getDebugOpenskyQueryKey = () => {
    return [
    `/debug/opensky`
    ] as const;
    }


export const getDebugOpenskyQueryOptions = <TData = Awaited<ReturnType<typeof debugOpensky>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof debugOpensky>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDebugOpenskyQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof debugOpensky>>> = ({ signal }) => debugOpensky({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof debugOpensky>>, TError, TData> & { queryKey: QueryKey }
}

export type DebugOpenskyQueryResult = NonNullable<Awaited<ReturnType<typeof debugOpensky>>>
export type DebugOpenskyQueryError = unknown


/**
 * @summary OpenSky Connectivity Test
 */

export function useDebugOpensky<TData = Awaited<ReturnType<typeof debugOpensky>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof debugOpensky>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getDebugOpenskyQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * Fetches METAR weather for London airports.
Cached for 30 minutes to respect upstream rate limits.
 * @summary Get London Airport Weather
 */
export type getWeatherResponse200 = {
  data: WeatherResponse
  status: 200
}

export type getWeatherResponseSuccess = (getWeatherResponse200) & {
  headers: Headers;
};
;

export type getWeatherResponse = (getWeatherResponseSuccess)

export const getGetWeatherUrl = () => {




  return `/weather`
}

export const getWeather = async ( options?: RequestInit): Promise<getWeatherResponse> => {

  return fetchClient<getWeatherResponse>(getGetWeatherUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetWeatherQueryKey = () => {
    return [
    `/weather`
    ] as const;
    }


export const getGetWeatherQueryOptions = <TData = Awaited<ReturnType<typeof getWeather>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getWeather>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWeatherQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWeather>>> = ({ signal }) => getWeather({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWeather>>, TError, TData> & { queryKey: QueryKey }
}

export type GetWeatherQueryResult = NonNullable<Awaited<ReturnType<typeof getWeather>>>
export type GetWeatherQueryError = unknown


/**
 * @summary Get London Airport Weather
 */

export function useGetWeather<TData = Awaited<ReturnType<typeof getWeather>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getWeather>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetWeatherQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}
