/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Flight Tracker at Home API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

/**
 * Single response for the main polling endpoint.
 */
export interface AircraftResponse {
  timestamp: number;
  cacheAgeSeconds: number;
  aircraft: AircraftState[];
  kpis: KPIs;
}

export type AircraftStateCallsign = string | null;

export type AircraftStateBaroAltitude = number | null;

export type AircraftStateGeoAltitude = number | null;

export type AircraftStateVelocity = number | null;

export type AircraftStateTrueTrack = number | null;

export type AircraftStateVerticalRate = number | null;

export type AircraftStateSquawk = string | null;

/**
 * One aircraft's state, transformed from OpenSky's positional array.
 */
export interface AircraftState {
  icao24: string;
  callsign: AircraftStateCallsign;
  originCountry: string;
  latitude: number;
  longitude: number;
  baroAltitude: AircraftStateBaroAltitude;
  geoAltitude: AircraftStateGeoAltitude;
  velocity: AircraftStateVelocity;
  trueTrack: AircraftStateTrueTrack;
  verticalRate: AircraftStateVerticalRate;
  onGround: boolean;
  squawk: AircraftStateSquawk;
  lastContact: number;
  isApproachingLhr: boolean;
}

export type KPIsApiHealth = typeof KPIsApiHealth[keyof typeof KPIsApiHealth];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KPIsApiHealth = {
  green: 'green',
  amber: 'amber',
  red: 'red',
} as const;

export interface KPIs {
  inboundLhr: number;
  throughputLast60Min: number;
  trackedAircraft: number;
  dataFreshnessSeconds: number;
  apiHealth: KPIsApiHealth;
}

/**
 * @summary Health
 */
export const getHealth = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.get(
      `/health`,options
    );
  }




export const getGetHealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }

    
export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: QueryKey }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = AxiosError<unknown>


/**
 * @summary Health
 */

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Get aircraft
 */
export const getAircraft = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AircraftResponse>> => {
    
    
    return axios.default.get(
      `/aircraft`,options
    );
  }




export const getGetAircraftQueryKey = () => {
    return [
    `/aircraft`
    ] as const;
    }

    
export const getGetAircraftQueryOptions = <TData = Awaited<ReturnType<typeof getAircraft>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAircraft>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAircraftQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAircraft>>> = ({ signal }) => getAircraft({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAircraft>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAircraftQueryResult = NonNullable<Awaited<ReturnType<typeof getAircraft>>>
export type GetAircraftQueryError = AxiosError<unknown>


/**
 * @summary Get aircraft
 */

export function useGetAircraft<TData = Awaited<ReturnType<typeof getAircraft>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAircraft>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAircraftQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
